### ISSUE TITLE
Update for Meteor 1.2?

### ISSUE THREAD

**Issue by rsskga** [reactioncommerce/reaction-core#182]
[koranin](https://github.com/koranin) has updated reaction-core locally to be compatible with Meteor 1.2. Is this desired? He's happy to create a pull-request.

**Comment by aaronjudd** [comment]
already updated, in `meteor-one-two` branch.  https://github.com/reactioncommerce/reaction-core/tree/meteor-one-two

**Comment by rsskga** [comment]
Ok, thanks @aaronjudd. We missed that. We need to familiarize ourselves with the project branches.

**Comment by aaronjudd** [comment]
I should be merging it soon. have one more issue with Bower to fix, and then it should be good.  The challenge is that if you want to run from the branches, you'll also need to correct (meteor-one-two) branch for all the packages.
