### ISSUE TITLE
Type Error when assigning Variant

### ISSUE THREAD

**Issue by BlastaRasta** [reactioncommerce/reaction-core#194]
I keep getting a TypeError when assigning a variant to the product.

```Exception while invoking method 'products/cloneVariant' TypeError: Cannot call method 'push' of undefined at server/methods/products.js:41:19```

Looks like this code has been rewritten in the last 3 days.

**Comment by spencern** [comment]
This issue should have been solved by my PRs 7cf8b980ffbf54a00d821eeb5dcd15430bdfd916 and  21b82ed6d5f5266dcd33b38fa26e0b36d44810a3

Are you sure you're on the latest version?

**Comment by aaronjudd** [comment]
This should be resolved, the latest versions with the fix for this are published, and available in master and development branches. (0.9.2)
