### ISSUE TITLE
When cleaning objects manually, `shopIdAutoValue()` will fail

### ISSUE THREAD

**Issue by tdecaluwe** [reactioncommerce/reaction-core#196]
Manually cleaning objects according to their schemas, will fail. Example:
 ```javascript
ReactionCore.Schemas.Tag.clean({name: 'tagName'});
```
This returns `{name: 'tagName'}`.

In the Tag schema, I can see `ReactionCore.shopIdAutoValue()` is being called, which throws the following error when called from the meteor shell:
```
TypeError: Object [object Object] has no method 'unset'
```

However the `clean()` function (supposedly wraps this call in a try block and) keeps quiet about this error. As a result, the object doesn't get cleaned. This also affects `schemaIdAutoValue()`.

I'm guessing somewhere the `simple-schema` package is not being passed the right context, but I can't figure out how to get this to work. What am I missing?

**Comment by aaronjudd** [comment]
I'm going to need to dig through some `simple-schema` docs on this,  `this.unset` is from  collections2 or simple-schema, so I would have expected this to work.  I've not actually tested the `clean` method though.

**Comment by tdecaluwe** [comment]
I'm putting you on the wrong track here, after some investigation I found out it's not throwing anything. I thought it was, since it does when you call it directly, but of course the context is missing.

The problem is that `ReactionCore.getShopId()` is not being called. If `ReactionCore` receives an object which already has a `shopId` it will overwrite it. I'll send over a PR.
