### ISSUE TITLE
Error in tags autocomplete: TypeError: undefined is not a function tags.coffee:27 

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction-core#71]
In v0.2.2 getSlug method is undefined

```
Uncaught TypeError: undefined is not a function tags.coffee:27 
$.autocomplete.sourcejquery-ui-1.10.4.custom.js:6244 
$.widget._searchjquery-ui-1.10.4.custom.js:401 
(anonymous function)jquery-ui-1.10.4.custom.js:6236 
$.widget.searchjquery-ui-1.10.4.custom.js:401 
(anonymous function)jquery-ui-1.10.4.custom.js:6217 
(anonymous function)jquery-ui-1.10.4.custom.js:730 handlerProxy
```

I didn't find this method in whole application https://github.com/reactioncommerce/reaction-core/search?utf8=%E2%9C%93&q=getSlug
It seems it's lost

**Comment by ramusus** [comment]
I found this method here https://github.com/ongoworks/meteor-speakingurl
This package has been added to the project by default, but method getSlug is not in global scope. It's undefined in my console.

**Comment by aaronjudd** [comment]
Updated the package, it's now available client and server from ongoworks:meteor-speakingurl
